import blogImages from "@/lib/blog-images.json";

// Blog images bypass /_next/image entirely and are served as static AVIF files
// generated by scripts/mirror-blog-images.mjs. The reasoning lives in the
// DEVICE_SIZES block of that script; the short version is that the optimizer
// hardcodes `effort: 3` and re-encodes an already-lossy WebP mirror, and doing
// both properly at build time is worth ~+1.3 dB at ~2% fewer bytes.
//
// A side effect worth having: no on-demand transcode means no cold-cache first
// visitor on a new post, and no optimizer cache entries to warm at all.
//
// Server-side only — this module imports the full manifest. The browser half
// is lib/blog-rendition.ts, which takes the widths as an argument.
const RENDITIONS = new Map<string, number[]>();
for (const entry of Object.values(
  blogImages as Record<
    string,
    { local: string; width: number; height: number; renditions?: number[] }
  >
)) {
  if (entry.renditions?.length) RENDITIONS.set(entry.local, entry.renditions);
}

// Undefined for images that failed to mirror (dead upstream URLs), which still
// render from their original remote location through the normal optimizer path.
export function renditionsFor(src: string): number[] | undefined {
  return RENDITIONS.get(src);
}
