import fs from "fs";
import path from "path";
import { cache } from "react";

// Velite output — type-safe data layer. Generated by `pnpm velite` from
// `md/blog/**/*.md`, `md/work/**/*.md`, `md/projects/**/*.md` via
// `velite.config.ts`. No runtime `readdirSync`/`readFileSync` for content.
import blogEntries from "../.velite/blog.json";
import projectEntries from "../.velite/projects.json";
import workEntries from "../.velite/work.json";

type VeliteBlog = (typeof blogEntries)[number];
type VeliteWork = (typeof workEntries)[number];
type VeliteProject = (typeof projectEntries)[number];

export type PostMeta = {
  slug: string;
  title: string;
  date: string;
  updated?: string;
  description?: string;
  cover?: string;
  link?: string | string[];
  tags?: string[];
  brand?: string;
  featured?: boolean;
  // Keeps the markdown record but drops the item from every listing
  // (home carousel, work grid, resume, sitemap, static params).
  hidden?: boolean;
};

// Module-private: every caller goes through one of the named accessors below,
// which is what keeps the folder string from leaking out as an API.
function readBySlug(
  folder: string,
  slug: string
): { meta: PostMeta; content: string } | null {
  let entry: VeliteBlog | VeliteWork | VeliteProject | undefined;

  if (folder === "blog") {
    entry = (blogEntries as VeliteBlog[]).find((e) => e.slug === slug);
  } else if (folder === "work") {
    entry = (workEntries as VeliteWork[]).find((e) => e.slug === slug);
  } else if (folder === "projects") {
    entry = (projectEntries as VeliteProject[]).find((e) => e.slug === slug);
  } else {
    return null;
  }

  if (!entry) return null;

  // Velite stores `body` as raw markdown; frontmatter fields are top-level.
  const anyEntry = entry as unknown as Record<string, unknown>;
  const meta: PostMeta = {
    slug: entry.slug,
    title: entry.title,
    date: entry.date,
    updated: anyEntry.updated as string | undefined,
    description: entry.description as string | undefined,
    cover: entry.cover as string | undefined,
    link: anyEntry.link as string | string[] | undefined,
    tags: anyEntry.tags as string[] | undefined,
    brand: anyEntry.brand as string | undefined,
    featured: anyEntry.featured as boolean | undefined,
    hidden: anyEntry.hidden as boolean | undefined,
  };

  return { meta, content: entry.body };
}

function parseDate(dateStr: string): number {
  if (!dateStr) return 0;

  // A full ISO date must not be split — the range handling below would take
  // "2024" off "2024-05-01" and sort every post in a year together.
  if (/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
    const date = new Date(dateStr);
    return isNaN(date.getTime()) ? 0 : date.getTime();
  }
  // Ranges like "Jan 2024 - May 2024" or "May 2023 - Present" sort by their
  // start date, so only the first half is parsed.
  const parts = dateStr.split(/[-–]/);
  const startDateStr = parts[0].trim();
  if (startDateStr.toLowerCase() === "present") {
    return Date.now();
  }
  const date = new Date(startDateStr);
  return isNaN(date.getTime()) ? 0 : date.getTime();
}

function countWords(markdown: string): number {
  const text = markdown.replace(/[#*`\[\]()>!|~-]/g, "").trim();
  return text.split(/\s+/).filter(Boolean).length;
}

// Reading time tracks the actual pre-generated narration (Edge TTS) audio
// length rather than a words-per-minute guess, since that is the real time a
// reader spends with the post either way.
function getNarrationDurationMs(
  slug: string,
  publishedAt: string
): number | null {
  const year = new Date(publishedAt).getFullYear();
  if (Number.isNaN(year)) return null;
  const narrationPath = path.join(
    process.cwd(),
    "public",
    "narration",
    String(year),
    `${slug}.json`
  );
  if (!fs.existsSync(narrationPath)) return null;
  try {
    const data = JSON.parse(fs.readFileSync(narrationPath, "utf8"));
    return typeof data.durationMs === "number" ? data.durationMs : null;
  } catch {
    return null;
  }
}

function readingTimeFromDurationMs(durationMs: number): number {
  return Math.max(1, Math.round(durationMs / 60000));
}

export type BlogPost = {
  title: string;
  slug: string;
  publishedAt: string;
  updatedAt?: string;
  brief?: string;
  cover?: string;
  content?: {
    markdown: string;
  };
  urls?: string[];
  readingTime?: number;
  wordCount?: number;
  tags?: string[];
  brand?: string;
};

export const getBlogPost = cache((slug: string): BlogPost | null => {
  const post = readBySlug("blog", slug);
  if (!post) return null;
  const wordCount = countWords(post.content);
  const narrationDurationMs = getNarrationDurationMs(
    post.meta.slug,
    post.meta.date
  );
  return {
    title: post.meta.title,
    slug: post.meta.slug,
    publishedAt: post.meta.date,
    updatedAt: post.meta.updated,
    brief: post.meta.description,
    cover: post.meta.cover,
    content: {
      markdown: post.content,
    },
    urls: post.meta.link
      ? Array.isArray(post.meta.link)
        ? post.meta.link
        : [post.meta.link]
      : undefined,
    readingTime:
      narrationDurationMs !== null
        ? readingTimeFromDurationMs(narrationDurationMs)
        : undefined,
    wordCount,
    tags: post.meta.tags,
    brand: post.meta.brand,
  };
});

export const getAllBlogPosts = cache((): BlogPost[] => {
  return (blogEntries as VeliteBlog[])
    .map((e) => getBlogPost(e.slug)!)
    .filter(Boolean)
    .sort(
      (a, b) =>
        new Date(b!.publishedAt).getTime() - new Date(a!.publishedAt).getTime()
    ) as BlogPost[];
});

export const getAllWorkItems = () => {
  const items = (workEntries as VeliteWork[]).map((e) => {
    const r = readBySlug("work", e.slug)!;
    return { item: r, dateValue: parseDate(r.meta.date) };
  });
  return items
    .sort((a, b) => b.dateValue - a.dateValue)
    .map(({ item }) => item);
};

/**
 * Repo-relative path of a post's markdown source, e.g. "blog/2023/foo.md",
 * for the one route that serves the file itself rather than its parsed body.
 *
 * Velite already recorded where every post lives, so nothing has to search the
 * filesystem for it — which matters because a recursive readdir with computed
 * paths is opaque to Next's output tracer, and it responds by bundling the
 * whole project into that route.
 */
export const getBlogSourcePath = cache((slug: string): string | null => {
  const entry = (blogEntries as VeliteBlog[]).find((e) => e.slug === slug);
  return entry ? `${entry.path}.md` : null;
});

export const getWorkItem = cache((slug: string) => readBySlug("work", slug));

/** Projects only — /work career entries are never returned. */
export const getProject = cache((slug: string) => readBySlug("projects", slug));

export const getAllProjects = () => {
  const items = (projectEntries as VeliteProject[])
    .map((e) => readBySlug("projects", e.slug)!)
    .filter((item) => !item.meta.hidden)
    .map((item) => ({ item, dateValue: parseDate(item.meta.date) }))
    .sort((a, b) => b.dateValue - a.dateValue)
    .map(({ item }) => item);
  return items;
};

const FEATURED_FALLBACK_COUNT = 5;

// Falls back to the newest few rather than returning nothing: an empty result
// would render the homepage showcase as an empty carousel (Embla initialising
// with zero slides) above an empty list, and the only way to cause that is to
// forget the flag on a new project.
export const getFeaturedProjects = () => {
  const projects = getAllProjects();
  const featured = projects.filter((item) => item.meta.featured === true);
  return featured.length > 0
    ? featured
    : projects.slice(0, FEATURED_FALLBACK_COUNT);
};
